TABLE_ (OW_PLAYERS)
   INT_    (PLAYER_ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_ (BATTLE_TAG,200) SQLDEFAULT("") NOT_NULL UNIQUE
   STRING_ (DISCORD_ID,200) SQLDEFAULT("") NOT_NULL UNIQUE
   STRING_ (COMMUN_NAME,200) SQLDEFAULT("")
END_TABLE

TABLE_(OW_EQUIPES)
   INT_    (EQUIPE_ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_ (EQUIPE_NAME, 200) SQLDEFAULT("") NOT_NULL UNIQUE
END_TABLE

TABLE_(OW_EQUIPES_PLAYERS)
   INT_ (EP_EQUIPE_ID) REFERENCES(OW_EQUIPES.EQUIPE_ID)
   INT_ (EP_PLAYER_ID) REFERENCES(OW_PLAYERS.PLAYER_ID)
END_TABLE
 
 TABLE_ (OW_EQUIPES_CREATOR)
 	INT_    (EQUIPES_ID) REFERENCES(OW_EQUIPES_PLAYERS.EP_EQUIPE_ID)
 	STRING_ (CREATOR_DISCORD_ID,200) SQLDEFAULT("")
 END_TABLE
 
TABLE_(OW_PLAYER_DATA)
   INT_ (DATA_ID) PRIMARY_KEY AUTO_INCREMENT
   INT_ (DATA_PLAYER_ID) REFERENCES(OW_PLAYERS.PLAYER_ID)
   TIME_ (RETRIEVE_DATE) SQLDEFAULT(CURRENT_DATE)
   INT_ (GAMES_PLAYED) SQLDEFAULT(-1)
   INT_ (LEVEL) SQLDEFAULT(-1)
   INT_ (RATING) SQLDEFAULT(-1)
   INT_ (MEDALS_COUNT) SQLDEFAULT(-1)
   INT_ (MEDALS_BRONZE) SQLDEFAULT(-1)
   INT_ (MEDALS_SILVER) SQLDEFAULT(-1)
   INT_ (MEDALS_GOLD) SQLDEFAULT(-1)
END_TABLE
