TABLE_ (OW_PLAYERS)
   INT_    (PLAYER_ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_ (BATTLE_TAG,200) SQLDEFAULT("") NOT_NULL UNIQUE
   STRING_ (DISCORD_ID,200) SQLDEFAULT("") NOT_NULL UNIQUE
   STRING_ (COMMUN_NAME,200) SQLDEFAULT("")
END_TABLE

TABLE_(OW_EQUIPES)
   INT_    (EQUIPE_ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_ (EQUIPE_NAME, 200) SQLDEFAULT("") NOT_NULL UNIQUE
END_TABLE

TABLE_(OW_EQUIPES_PLAYERS)
   INT_ (EP_EQUIPE_ID)REFERENCES_CASCADE_(OW_EQUIPES,EQUIPE_ID)
   INT_ (EP_PLAYER_ID)REFERENCES_CASCADE_(OW_PLAYERS,PLAYER_ID)
END_TABLE
 
 TABLE_ (OW_EQUIPES_CREATOR)
 	INT_    (EC_EQUIPES_ID)REFERENCES_CASCADE_(OW_EQUIPES,EQUIPE_ID)
 	INT_    (EC_PLAYER_ID) REFERENCES_CASCADE_(OW_PLAYERS,PLAYER_ID)
 	BOOL_   (EC_ADMIN) SQLDEFAULT(TRUE)
 END_TABLE
 
TABLE_(OW_PLAYER_DATA)
   INT_ (DATA_ID) PRIMARY_KEY AUTO_INCREMENT 
   INT_ (DATA_PLAYER_ID)REFERENCES_CASCADE_(OW_PLAYERS,PLAYER_ID)
   DATE_ (RETRIEVE_DATE) 
   INT_ (GAMES_PLAYED) SQLDEFAULT(-1)
   INT_ (LEVEL) SQLDEFAULT(-1)
   INT_ (RATING) SQLDEFAULT(-1)	
   INT_ (MEDALS_COUNT) SQLDEFAULT(-1)
   INT_ (MEDALS_BRONZE) SQLDEFAULT(-1)
   INT_ (MEDALS_SILVER) SQLDEFAULT(-1)
   INT_ (MEDALS_GOLD) SQLDEFAULT(-1)
END_TABLE